language: node_js
node_js:
- iojs
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
env: global:GH_TOKEN=c4d321258c51f4efb309a89ac52a05bd49b63a51
deploy:
  provider: npm
  email: david@excellenteasy.com
  skip_cleanup: true
  api_key:
    secure: E3W1FcH0PD0QaSLhMjGnCAmdizQBZJlBYUc/TOZqh74gNOkerAxajtYaCLqCIR/qp9iSlbFfvFe/2Fn9GTmjK+v3QGmz6kOu44t+HNYBS2fgKNJG5ibOeW1hRtP6ceChKy1uXK7U3ttWogB+dhhMk1P1WPr1uD9+cIoMH9Q2N/M=
  on:
    branch: master
    repo: excellenteasy/ios-icons
